package.json, yarn.lock
See https://github.com/danger/danger-js/pull/885
=> Fixes danger failing on circleci

package.json
[#168538628]
Remove env-config.js file during npm start process to keep project root clean
=> [#168538628] - Remove env-config.js

Dockerfile, nginx.conf
added nginx.conf
added Dockerfile command to copy nginx.conf into nginx
=> [#168539271] - Always return index.html from nginx

README.md
[#168539996]
update readme file
=> [#168539996] - update README file

.gitignore
=> [#168540149]

src/components/DelegateDashboard/DelegateDashboard.tsx
created dummy button to go to sign up page
=> [#168579686]

src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx
[#168630498]
fixed param name
fixed router path
fixed dummy button route
rebased master
=> [#168630498] - fix back buttons

src/components/Home/Home.tsx, src/components/Home/HomeLoginButton/HomeLoginButton.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/SpidLogin/SpidLogin.css, src/components/SpidLogin/SpidLogin.tsx, src/scss/_custom.scss
added custom style to adapt pages to older screens (lower resolution)
fixed component style to adapt margins and paddings to lower resolutions
=> [#168425178] fix classes for lower resolution

src/components/Home/Home.tsx
reduced height of io logo in homepage to 60px
=> [#168425186] resized io logo in home

src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx
disable button if some data is not set in step 1
=> [#168660935] disable sign up step 1 button

src/components/AppAlert/AppAlert.css, src/components/AppAlert/AppAlert.tsx, src/components/DefaultContainer/DefaultContainer.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/context/alert-context.tsx, src/context/token-context.tsx, src/index.tsx
added AppAlert component
added AlertContext to Registration step one
added alert context
=> [#168784342] add alert to show messages

src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx
added structure for registration step 2
=> [#168752311] initial structure for registration step 2

package.json, src/index.tsx, yarn.lock
added new package for react polyfills for ie 11
added import in index.tsx
=> [#168897544] added react polyfills for ie 11

locales/en/index.yml, locales/it/index.yml, src/components/CentralHeader/CentralHeader.tsx, src/components/Home/Home.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/Registration/RegistrationStepOne/SearchInstitutions.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx, src/components/SpidLogin/SpidLogin.tsx, src/i18n.ts
[#168898538] added translation for all components
=> [#168898538] add translations

src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx
fixed button to go back in registration step one to open modal for confirmation
=> [#168897542] fix back button step one registration

src/components/Registration/RegistrationStepOne/SearchInstitutions.css, src/components/Registration/RegistrationStepOne/SearchInstitutions.tsx
increased debounce
aligned text
search after 5 letters
=> [#168701836] fixed typeahead

src/components/Registration/RegistrationStepOne/SearchInstitutions.css
made scrollbar always visible and highlighted in blue
=> [#168752265] typeahead scrollbar

locales/en/index.yml, locales/it/index.yml, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/Registration/RegistrationStepOne/SearchInstitutions.css, src/components/Registration/RegistrationStepOne/SearchInstitutions.tsx
added initial text in registration step 1
added button "Ricerca" to make first input more visible
=> [#168752156] added text and search button

src/components/CentralHeader/CentralHeader.css, src/components/CentralHeader/CentralHeader.tsx, src/components/DefaultContainer/DefaultContainer.tsx, src/components/SlimHeader/SlimHeader.tsx, src/scss/_custom.scss
now header scrolls with the page
=> [#168930712] header not fixed

src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/Registration/RegistrationStepOne/SearchInstitutions.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx, src/components/SpidLogin/SpidLogin.tsx
increased distance between elements and from the bottom of the page
=> [#168930789] increased distance between elements

src/App.tsx, src/components/ScrollToTop.tsx
added component to scroll to top of the page
added component to App component inside Router
=> [#168930666] added HOC to scroll to top

locales/en/index.yml, locales/it/index.yml, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx, src/components/SlimHeader/SlimHeader.tsx, src/components/SpidLogin/SpidLogin.tsx
all external links open in new tab
=> [#168930753] links in new tab

src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx
added functions to save and update sign up step 2 fields values
=> [#168752325] added logic to sign up step 2 fields

.env.io-onboarding-pa-api.development
fixed api env variables file for docker local testing
=> [#169036900] new env variables

server/db.json, src/components/Dashboard/Dashboard.tsx
added get profile call in dashboard
added correct token set and management
added mock response for json-server
=> [#169127770] get profile integration

.circleci/config.yml, package.json, server/db.json, src/App.tsx, src/components/CentralHeader/CentralHeader.tsx, src/components/Dashboard/Dashboard.tsx, src/components/DefaultContainer/DefaultContainer.tsx, src/components/Home/Home.tsx, src/components/Home/HomeLoginButton/HomeLoginButton.tsx, src/components/LoadingScreen/LoadingScreen.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/Registration/RegistrationStepOne/SearchAdministrations.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx, src/components/SignUpContainer/SignUpContainer.tsx, src/components/SlimHeader/SlimHeader.tsx, src/components/SpidLogin/SpidLogin.tsx, src/components/SpidLogin/SpidLoginButton/SpidLoginButton.tsx, src/i18n.ts, src/index.tsx, tslint.json
fixed all components for circleci automatic checks and to fix all linting problems
added rule to tslint
excluded auto generated file for transaltions from linting
add circleci config command to generate all
added rules exceptions in tslint file
added new structure for administration search response and relative mocked data
added fixes for api changes (snakecase for selected pec label)
=> [#169186182] fixes for circleci and linter

server/db.json, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx
fixed naming for selected pec label after API refactoring
=> [#169313082] fixed pec checkbox

locales/en/index.yml, locales/it/index.yml, src/components/CentralHeader/CentralHeader.tsx, src/components/Home/Home.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/Registration/RegistrationStepOne/SearchAdministrations.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx, src/components/SpidLogin/SpidLogin.tsx
added common section to translation files and refactored redundant strings
fixed components with new translations
fixed central header profile dropdown for long strings
fixed button in spid login page
=> [#169342054] restructure translations files

locales/en/index.yml, locales/it/index.yml, server/db.json, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx
added functions and mock data to save administration on confirm at sign up step 2
=> [#168752341] save administration

locales/en/index.yml, locales/it/index.yml, src/components/BackButton/BackButton.tsx, src/components/CentralHeader/CentralHeader.tsx, src/components/DefaultContainer/DefaultContainer.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx, src/components/SpidLogin/SpidLogin.css, src/components/SpidLogin/SpidLogin.tsx, src/components/UserProfile/UserProfile.tsx, src/components/UserSettings/UserSettings.tsx, src/scss/_custom.scss
added user profile page with data from user profile service
added locales strings
added BackButton component to externalize code for back button (chevron left + text)
added class for card
=> [#169285325] user profile page

locales/en/index.yml, locales/it/index.yml, server/db.json, src/components/Dashboard/Dashboard.tsx, src/components/Modal/AddMailModal.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/SpidLogin/SpidLoginButton/SpidLoginButton.tsx
added modal to prompt user to add a work mail (or confirm spid one) at first login
=> [#168752410] add work mail modal

.env.io-onboarding-pa-api.development, src/components/Modal/AddMailModal.tsx
added logic to activate modal button to add mail
added new env variables for api (needed for local testing with docker)
=> [#168752421] activate add work mail button

locales/en/index.yml, locales/it/index.yml, src/components/Dashboard/Dashboard.tsx, src/components/DefaultContainer/DefaultContainer.tsx, src/components/Modal/AddMailModal.tsx
added work mail update from modal at first login
added new alert texts
=> [#168752431] update user mail with api call to update profile

locales/en/index.yml, locales/it/index.yml, src/App.tsx, src/components/LoadingPage/LoadingPage.css, src/components/LoadingPage/LoadingPage.tsx, src/components/LoadingScreen/LoadingScreen.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/ScrollToTop.tsx, src/context/alert-context.tsx, src/context/loading-page-context.tsx, src/index.tsx
added component for loading/informative page for user
added translations
removed unused component
added call to loading page after registration step 2
added loading page context to create loading pages with different content
=> [#169647021] added loading page

locales/en/index.yml, locales/it/index.yml, src/components/Registration/RegistrationStepThree/RegistrationStepThree.tsx
added api call to send documents for institution registration at sign un step 3 confirmation
added translations
=> [#169647056] sending documents for institution registration

.env.io-onboarding-pa-api.development, locales/en/index.yml, locales/it/index.yml, src/clients/api.ts, src/components/CentralHeader/CentralHeader.tsx, src/components/DefaultContainer/DefaultContainer.tsx, src/components/Home/HomeLoginButton/HomeLoginButton.tsx, src/components/Modal/AddMailModal.tsx, src/components/Modal/LogoutModal.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepThree/RegistrationStepThree.tsx, src/components/UserProfile/UserProfile.tsx, src/context/logout-modal-context.tsx, src/utils/api-utils.ts
added logout modal both for automatic logout in case of expired token and for user triggered logout
added translations for logout modal
added custom classes for logout service (to solve problem with code 204, tracked in story https://www.pivotaltracker.com/story/show/169836423)
added logoutModalContext
fixed service response in case of error 201 (show logout modal before redirecting to homepage)
added token management to avoid login in case token has not expired yet
added new env variables
=> [#169645680] added logout modal and logout management

README.md, src/components/BackButton/BackButton.tsx, src/components/DefaultContainer/DefaultContainer.tsx, src/components/Modal/LogoutModal.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx, src/components/Registration/RegistrationStepThree/RegistrationStepThree.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx
fixed cancel button in registration steps (now user is redirect to dashboard)
fixed back button in step 1 of registration (user is now asked to confirm to return to dashboard)
fixed alertText string of api call error case as suggested in https://github.com/teamdigitale/io-onboarding-pa/pull/58#discussion_r349937898
fixed typo in README
=> [#169119078] fixed cancel and back button in registration steps

locales/en/index.yml, locales/it/index.yml, server/db.json, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx
added translations
added fields to mock results
added check to disable radio buttons and show alert in case administration is already registered
=> [#168783449] added registration step 1 logic for registered administrations

locales/en/index.yml, locales/it/index.yml, package.json, src/components/Modal/AddMailModal.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx, src/utils/value-of.ts, yarn.lock
added library react form hook
added strings for errors
added hook and form management in AddMailModal, RegistrationStepOne and RegistrationStepTwo
=> [#168752335] form fields validation

Dangerfile.ts, package.json, scripts/make-locales.ts, src/App.tsx, src/__tests__/App.test.tsx, src/clients/api.ts, src/components/AppAlert/AppAlertTemplate.tsx, src/components/BackButton/BackButton.tsx, src/components/CentralHeader/CentralHeader.tsx, src/components/Dashboard/Dashboard.tsx, src/components/Dashboard/OrganizationCard.tsx, src/components/DefaultContainer/DefaultContainer.tsx, src/components/Home/Home.tsx, src/components/LoadingPage/LoadingPage.tsx, src/components/Modal/AddMailModal.tsx, src/components/Modal/LogoutModal.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepButtons/RegistrationStepButtons.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/Registration/RegistrationStepOne/SearchAdministrations.tsx, src/components/Registration/RegistrationStepThree/RegistrationStepThree.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx, src/components/SlimHeader/SlimHeader.tsx, src/components/SpidLogin/SpidLogin.tsx, src/components/SpidLogin/SpidLoginButton/SpidLoginButton.tsx, src/components/UserProfile/UserProfile.tsx, src/i18n.ts, src/index.tsx, tslint.json, yarn.lock
fixes imports order and linting
=> [#170473306] fixes linting

package.json, src/components/Modal/AddMailModal.tsx, src/components/Registration/RegistrationStepOne/RegistrationStepOne.tsx, src/components/Registration/RegistrationStepTwo/RegistrationStepTwo.tsx, yarn.lock
upgrades react-hook-form package
=> [#170442909] upgrade react hook form

locales/en/index.yml, locales/it/index.yml
changes 'delegato' into 'gestore'
=> [#170102690] fixes profile label

src/clients/api.ts, src/components/Dashboard/OrganizationCard.tsx, src/components/Registration/RegistrationContainer.tsx, src/components/Registration/RegistrationStepThree/RegistrationStepThree.tsx
this PR does not a real refactoring of the requests status (which is tracked by https://www.pivotaltracker.com/story/show/170671730) but lets the frontend compile against the new api.
=> [#170671732] hotfix: ignore organization registration status

.circleci/config.yml
deploy from circleci to azure website storage account
=> [#170574895] setup circleci deployment
